language: csharp
solution: Onboarding.sln
notifications:
 email:
   on_success: always
   on_failure: always
 slack: srboeingdotnet:UIU3Bl3s8QViLrC2yS7GV9NI
mono: none
dotnet: 2.1
script:
  - dotnet restore
after_success:
  - /bin/bash ./deploy.sh
#  - dotnet test keeptest/