version: '3.4'

services:
  web:
    build: ./Onboarding
    # ports:
    #     - "5000:80"
    depends_on:
        - db
    # volumes:
    #   - "/machine_config:/app/machine_config"
    labels:
     - "SERVICE_8080_NAME=onboarding-service"
     - "SERVICE_TAG=rtm-serviceTag"
  #  expose:
  #    - "5000"
    restart: on-failure
    # network_mode: host
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "YourStrongP@ssword"
      ACCEPT_EULA: "Y"
